### ISSUE TITLE
Ports download unifi

### ISSUE THREAD

**Issue by ghost** [unofficial-unifi/unifi-pfsense#127]
Can ports be utilized to download the unifi package?

http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/unifi5-5.9.29.txz

**Comment by itnetsec** [comment]
Asking regarding being able to grab the latest and greatest of the UniFi software. I was reading that y'all found no way to grab the latest.  Looking at this it looks like they're having to do the same thing and update the version manually.

https://svnweb.freebsd.org/ports/head/net-mgmt/unifi5/Makefile?view=co

**Comment by tong2x** [comment]
too old and irelevant for now since we are already in 6.2 and this is 5.9
