### ISSUE TITLE
Install broken on netgate sg-1100 with pfSense 2.4.4-p2

### ISSUE THREAD

**Issue by Steve973** [unofficial-unifi/unifi-pfsense#137]
I tried to run the install script on my netgate sg-1100 that is running pfsense 2.4.4-RELEASE-p2 (arm64).  I had a lot of certificate errors, and it was not able to locate Java.  The installation seemed to be so broken that I don't really know where to start to resolve them.  Is this meant to work on that platform?

**Comment by Talidorn** [comment]
I attempted to install.  No luck.  Just as stated above.  Certificate verification failed

**Comment by simonpatap0n** [comment]
Sg-100 with 2.4.5 broken too

https://pastebin.com/qF18177U

Simon

**Comment by jmbwell** [comment]
Thank you. It's a different architecture. We'd need to make changes for it to pull ARM dependencies. Not sure what that would entail at this point, since we're having to pull together dependencies piecemeal as it is. Happy to look at PRs though!

**Comment by tong2x** [comment]
no more updates, closing
