### ISSUE TITLE
Upgrading to pfsense 2.5 -- controller won't start, missing mongodb

### ISSUE THREAD

**Issue by jayjanssen** [unofficial-unifi/unifi-pfsense#232]
Hi, I just upgraded my pfsense to 2.5, but the controller would not fully startup.  I determined that mongo was not starting and running 'mongo' on the command line was giving some kind of SSL error.

I checked pkg to re-install mongo fresh but it wasn't there.  It looks like pfsense 2.5 decided to disable the FreeBSD pkg repos.  I had to modify the files in /usr/local/etc/pkg/repos to re-enable the FreeBSD repo, then I was able to re-install mongo.  After that, the controller started up fine.  

I'm unsure if I should leave the FreeBSD repos enabled or not, or if that will cause any conflicts with the PFsense repos (they probably disabled FreeBSD for a reason).  

Anyway -- I figured I'd document my findings here for the next guy.  I'm not sure what the right patch would be to the script to address this, but it's probably non-trivial.

**Comment by jayjanssen** [comment]
For the record:

I removed the 'FreeBSD' section of: /usr/local/etc/pkg/repos/pfSense.conf, it was something like:

> FreeBSD: { enabled: no }

I also copied over  /usr/local/etc/pkg/repos/FreeBSD.conf from /etc/pkg/FreeBSD.conf

Perhaps not the most elegant changes, but it got the job done.

Then:

> pkg update
> pkg install mongodb36

**Comment by PolarNettles** [comment]
I hit the same issue after updating to 2.5.1 from 2.4.5. The version of mongodb I had previously installed (3.6.21) was linked against an older version of OpenSSL that was removed in the new pfSense release.

The only fix I found was to upgrade to the latest mongodb, which meant re-enabling the main repos.

**Comment by tong2x** [comment]
no more updates, closing
