### ISSUE TITLE
python37 install fails: Missing dependency 'mpdecimal'

### ISSUE THREAD

**Issue by alexw1982** [unofficial-unifi/unifi-pfsense#237]
Script throws an error on 2.5.1 `Missing dependency 'mpdecimal'`

```
package python37 is already installed, forced install
pkg: Missing dependency 'mpdecimal'

Failed to install the following 1 package(s): https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/python37-3.7.10_1.txz
```

I am stuck not finding any of the unifi devices on my network (pfsense --> poe lite 16 --> ap a6 lite) - however my gut tells me that this is not related...

**Comment by ReinaldoFeitosa** [comment]
Fix in new install 2.6.26
