### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by ahmedakkaya** [unofficial-unifi/unifi-pfsense#245]
hi.

https://network.unifi.ui.com/   unifi network portal device connect launch error Connection failed.

help me?

**Comment by tong2x** [comment]
maybe you would like to give far more details on yourproblem

**Comment by gnkidwell** [comment]
> hi.
> 
> https://network.unifi.ui.com/   unifi network portal device connect launch error Connection failed.
> 
> help me?

Are you referring to cloud access? This is not functional on BSD installations... Therefore, if this feature is critical you will need a Linux or Windows controller instead...

**Comment by ahmedakkaya** [comment]
> > Merhaba.
> > https://network.unifi.ui.com/    unifi ağ portalı cihazı bağlan başlatma hatası Bağlantı başarısız oldu.
> > bana yardım et?
> 
> Bulut erişiminden mi bahsediyorsunuz? Bu, BSD kurulumlarında işlevsel değildir... Bu nedenle, bu özellik kritikse, bunun yerine bir Linux veya Windows denetleyicisine ihtiyacınız olacak...



> > hi.
> > https://network.unifi.ui.com/   unifi network portal device connect launch error Connection failed.
> > help me?
> 
> Are you referring to cloud access? This is not functional on BSD installations... Therefore, if this feature is critical you will need a Linux or Windows controller instead...

is there any work around this error

Shall I wait
is there hope

or will it never work?

**Comment by tong2x** [comment]
no other updates as of this time
issue is a know non functional feature on BSD

**Comment by ahmedakkaya** [comment]
> no other updates as of this time issue is a know non functional feature on BSD

thanks.
