### ISSUE TITLE
device disconnected

### ISSUE THREAD

**Issue by ahmedakkaya** [unofficial-unifi/unifi-pfsense#246]
hi.
I installed unifi 6.26 in pfsense 2.5.2.
I have added my unifi devices.
When I restart pfsense it cannot connect to my unifi devices?

https://ibb.co/5LNhHWN

**Comment by tong2x** [comment]
your switchPOE seem to be connected...
is the AP physically disconnected from your network?
via ping on local network, it the AP active?
in PFSense diagnostics try ping the AP also
