### ISSUE TITLE
Web UI access blocked by firewall 

### ISSUE THREAD

**Issue by trooper** [unofficial-unifi/unifi-pfsense#268]
After switching to a Dual WAN setup, my  Unifi Controller on my OPNsense server is no longer accessible from LAN. 

I can still `curl https://localhost:8443` from firewall's shell, but external access no longer works. 

Disabling firewall completely works. 

I have tried explicitly allowing inbound traffic on ports `8443` and `8080`, but that did not help at all.

Any idea what kind of firewall rules do we need to set up for Unifi Controller to work?

**Comment by tong2x** [comment]
you ahve added NAT port forward rules? on both your WAN?

**Comment by trooper** [comment]
Sorry, which port forward rules? Does Unifi Controller need external port tunnelling? I was hoping that it only needs local LAN access?

**Comment by tong2x** [comment]
oh you mean you cant access it locally?
same IP and subnet with the machine your using?
in your firewall rules for the adapter in which your unifi and PC is conencted, you must allow DNS to any at top.
last rule will be to allow all connections (unless you have other specific rule)

**Comment by tong2x** [comment]
no more updates, closing
