### ISSUE TITLE
ip address of the controller ...

### ISSUE THREAD

**Issue by hacesoft** [unofficial-unifi/unifi-pfsense#273]
hi
is there any way to change the IP address of the UniFi controller? currently has the same firewall as just a different port. I would like to have the controller installed on the same machine as PfSense, but to run at a different address, it is ideally also installed on a different VLAN .... Is it possible or do I have to install the UniFi controller on other HW, such as raspberries?

Thanks for the information that will lead to the question of my question :).

**Comment by jmbwell** [comment]
UniFi controller listens on all addresses. Add a virtual IP to pfsense, or configure a VLAN interface. See the pfsense docs.

https://docs.netgate.com/pfsense/en/latest/firewall/virtual-ip-addresses.html

https://docs.netgate.com/pfsense/en/latest/vlan/configuration.html
