### ISSUE TITLE
Port 8080 not available

### ISSUE THREAD

**Issue by ihsanCurse** [unofficial-unifi/unifi-pfsense#277]
I want to use unfi. 

I uninstall and install with the script. 

I get the message 
```
Port 8080 not available
```

I checked if the port is used 

```
$ ps aux | grep "8080"
root    41445   0.0  0.0 1060992   3212  0  R+   11:21    0:00.00 grep 8080
```
 I am on ` OPNsense.localdomain: OPNsense 21.7.7 (amd64/OpenSSL) `

**Comment by schmilmo** [comment]
I got the same issue
also cannot get access GUI

**Comment by tong2x** [comment]
try to reboot twice if the would work, do you happen to know if you are using that port (other application)?

normally it should resolved after reboot

**Comment by schmilmo** [comment]
It's running now but when I try to see in on https://192.168.100.1:8443 I get 404 ?

**Comment by tong2x** [comment]
what verison of unifi are you using?

**Comment by schmilmo** [comment]
version 6.5.55
I found out that the mongoDB was corrupted.
It happened after a power outage.
We had a few power outages and each time the DB was corrupted

**Comment by tong2x** [comment]
better get a UPS for your equipment
then again if the power outage is too long, UPS migth not help

**Comment by tong2x** [comment]
btw is this is resolved already?

**Comment by tong2x** [comment]
no more updates to the issue
