### ISSUE TITLE
controller new version 7.0.23

### ISSUE THREAD

**Issue by hacesoft** [unofficial-unifi/unifi-pfsense#282]
Have a nice day,
I modified the UniFi script to the latest version 7.0.23, I saved it on GitHub, I created an alias at https://tinyurl.com/ and then I used the fetch display and it doesn't work for me, it makes a mistake in the console:

   Bpssh: Syntax error: newline unexpected (expecting word)

have no idea what I did wrong?

script ma alias: https://tinyurl.com/mwp2rxku

thanks for the info.

**Comment by gnkidwell** [comment]
You need to point the tinyurl to the raw link which is here... https://raw.githubusercontent.com/hacesoft/UniFi/main/install-unifi_7.0.23.sh

**Comment by hacesoft** [comment]
Thank you.
