### ISSUE TITLE
Installing on pfsense 2.6 failed - fixed

### ISSUE THREAD

**Issue by ChiefZigZag** [unofficial-unifi/unifi-pfsense#296]
It failed installing openjdk8, I had to manually ` pkg add brotli` and then it worked fine.

**Comment by tong2x** [comment]
which install script you run?

**Comment by ChiefZigZag** [comment]
> which install script you run?

fetch -o - https://git.io/j7Jy | sh -s

As per readme

**Comment by tong2x** [comment]
you may want to the newer scripts in the pull request,

**Comment by vitorarend** [comment]
Running `pkg install brotli` fixed for me as well on pfSense 2.6.0

**Comment by tong2x** [comment]
I'll add brotli as additional package in the latest beta firmware

**Comment by slmingol** [comment]
I'm still on pfsense 2.5.0 and needed to do this as well going from UniFi 7.2.92 using this PR - https://github.com/unofficial-unifi/unifi-pfsense/pull/306
