### ISSUE TITLE
Pfsense  2.4.5p1 Can't install Error Message: pkg already bootstrapped at /usr/local/sbin/pkg

### ISSUE THREAD

**Issue by chumunga** [unofficial-unifi/unifi-pfsense#300]
I already manually uninstall with:
  rm -rf /usr/local/UniFi
  rm /usr/local/etc/rc.d/unifi.sh

[2.4.5-RELEASE][admin@pfbox.mylan]/root/unifi_controller: fetch -o - https://git.io/j7Jy | sh -s
-                                                     7704  B   38 MBps    00s
FreeBSD pkgng not installed. Installing...
pkg already bootstrapped at /usr/local/sbin/pkg
 done.
ERROR: pkgng installation failed. Exiting.
[2.4.5-RELEASE][admin@pfbox.mylan]/root/unifi_controller:

**Comment by chumunga** [comment]
I assume the issue was with 2.4.5p1, i decided to upgrade to 2.5.2, but the server decided i should use 2.6 and brick my system.

So fresh wiped disk and reinstalled. Ran the script except when i try to start the service i get this.

[2.6.0-RELEASE][admin@pfSense.bear.local]/root: service unifi.sh start
Starting UniFi controller.
eval: /usr/local/bin/java: not found

Any suggestion would be greatly appreciated

**Comment by tong2x** [comment]
which unifi installer you used?

is the installer from the newer beta scripts

**Comment by chumunga** [comment]
I believe I see the issue now, i missed the part that explains not to use if using zfs. Due to issues with 2.6 stability i cant get GPT install working. I am actually using 2.5.2 ZFS so i think i am disqualified from using this.

I was just using this from the readme page.

fetch -o - https://git.io/j7Jy | sh -s

**Comment by tong2x** [comment]
if you want to try the betas
https://github.com/unofficial-unifi/unifi-pfsense/pull/292

the readme installer is a bit old but should be good for most users.

**Comment by tong2x** [comment]
closing no more updates
