### ISSUE TITLE
Does not run on netgate SG-2100

### ISSUE THREAD

**Issue by mentaluproar** [unofficial-unifi/unifi-pfsense#305]
I get errors when I try to install on a 2100. It seems it doesn’t want to pull some of the dependencies from the repository, throwing errors about certificates and denying a packages exists.

I was able to make it work by first changing the packagesite extension because there is no pkg file for it on aarch64. Then I manually had to install packages by using curl to fetch from the repo what it claims I cannot find and then installing those. I then edited the script to comment out the addpkgs and run only the code to come figure it. Then it worked. 

Obviously this isn’t ideal. Below is what I get when I try to run the script normally

[22.05-RELEASE][root@router.there.local]/root: fetch -o - https://git.io/j7Jy | sh -s
-                                                     7673  B 1092 kBps    00s
sh: mongod: not found
Mounting new filesystems... done.
Removing discontinued packages...
Usage: pkg lock [-lqy] [-a|[-Cgix] <pkg-name>]
       pkg lock --has-locked-packages
       pkg unlock [-lqy] [-a|[-Cgix] <pkg-name>]
For more information see 'pkg help lock'.
Usage: pkg delete [-DfnqRy] [-Cgix] <pkg-name> ...
       pkg delete [-Dnqy] -a
 
For more information see 'pkg help delete'.
done.
Installing required packages...
fetch: https://pkg.freebsd.org/FreeBSD:12:aarch64/latest/packagesite.pkg: Not Found
tar: Error opening archive: Failed to open 'packagesite.pkg'
grep: packagesite.yaml: No such file or directory
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
1078734848:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/var/jenkins/workspace/pfSense-img-build/BUILD_NODE/aarch64/OS_MAJOR_VERSION/freebsd12/PLATFORM/aws/sources/FreeBSD-src-plus-RELENG_22_05/crypto/openssl/ssl/statem/statem_clnt.c:1916:
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
1078734848:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/var/jenkins/workspace/pfSense-img-build/BUILD_NODE/aarch64/OS_MAJOR_VERSION/freebsd12/PLATFORM/aws/sources/FreeBSD-src-plus-RELENG_22_05/crypto/openssl/ssl/statem/statem_clnt.c:1916:
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
1078734848:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/var/jenkins/workspace/pfSense-img-build/BUILD_NODE/aarch64/OS_MAJOR_VERSION/freebsd12/PLATFORM/aws/sources/FreeBSD-src-plus-RELENG_22_05/crypto/openssl/ssl/statem/statem_clnt.c:1916:
pkg: https://pkg.freebsd.org/FreeBSD:12:aarch64/latest/: Authentication error
[22.05-RELEASE][root@router.there.local]/root:

**Comment by tong2x** [comment]
no more updates
