### ISSUE TITLE
OPNsense 23.1.5_4-amd64 Failed to install the following 1 package(s): https://pkg.freebsd.org/FreeBSD:13:amd64/latest/

### ISSUE THREAD

**Issue by smartonaut** [unofficial-unifi/unifi-pfsense#315]
Hi running on a ZBOX with Intel(R) Core(TM) i3-4130T CPU @ 2.90GHz (2 cores, 4 threads)
OPNsense 23.1.5_4-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

The script stop but  i dont know what is missing.

root@Smartnet:~ # fetch -o - https://git.io/j7Jy | sh -s
-                                                     7687  B 6666 kBps    00s
sh: mongod: not found
Mounting new filesystems... done.
Removing discontinued packages...
Usage: pkg lock [-lqy] [-a|[-Cgix] <pkg-name>]
       pkg lock --has-locked-packages
       pkg unlock [-lqy] [-a|[-Cgix] <pkg-name>]
For more information see 'pkg help lock'.
Usage: pkg delete [-DfnqRy] [-Cgix] <pkg-name> ...
       pkg delete [-Dnqy] -a

For more information see 'pkg help delete'.
 done.
Installing required packages...
packagesite.pkg                                       6712 kB 8799 kBps    01s
x packagesite.yaml.sig
x packagesite.yaml.pub
x packagesite.yaml
Package png-1.6.39 already installed.
Package brotli-1.0.9,1 already installed.
Package freetype2-2.12.1_2 already installed.
Package fontconfig-2.14.2,1 already installed.
Package alsa-lib-1.2.2_1 already installed.
Package mpdecimal-2.5.1 already installed.
Package python37-3.7.16_2 already installed.
Package libfontenc-1.1.4 already installed.
Package mkfontscale-1.2.1 already installed.
Package dejavu-2.37_1 already installed.
Package giflib-5.2.1 already installed.
Package xorgproto-2022.1 already installed.
Package libXdmcp-1.1.3 already installed.
Fetching : 100%    2 KiB   2.3kB/s    00:01
pkg: archive_read_open_filename(/tmp/.XXXXX): Unrecognized archive format

Failed to install the following 1 package(s): https://pkg.freebsd.org/FreeBSD:13:amd64/latest/
root@Smartnet:~ #

can help me someone Please.

**Comment by tong2x** [comment]
#311 please try some of the other firmware
if those would work

**Comment by smartonaut** [comment]
i remark the error Paket (#AddPkg libpthread-stubs) out, and the install complete, but i cant login to my Ubiquiti Account, local all work fine.

**Comment by tong2x** [comment]
even if remote is enabled? maybe something blocking the ports?

**Comment by ModMike** [comment]
Having the same issue on opnsense

**Comment by tong2x** [comment]
you may want try the newer firmware #311

**Comment by ModMike** [comment]
Isn't it 7.4.156? That's what the script pulls in.

**Comment by tong2x** [comment]
#319 should pull 7.4.154
#311 should have  7.4.156

will try to integrate that in #319 for testing
