### ISSUE TITLE
eval: /usr/local/bin/java: not found

### ISSUE THREAD

**Issue by theotherguy2175** [unofficial-unifi/unifi-pfsense#316]
Starting UniFi controller.
eval: /usr/local/bin/java: not found

How do you re-install Java on FreeBSD with PFSense?

**Comment by wyrickre** [comment]
The [install-unifi.sh](https://github.com/unofficial-unifi/unifi-pfsense/blob/master/install-unifi/install-unifi.sh) script should have done that for you.

**Comment by theotherguy2175** [comment]
It doesn't.

**Comment by tong2x** [comment]
please try the java trouble shooting section or remove and reinstall everything
are you on pfsense or opnsense? what version?

**Comment by theotherguy2175** [comment]
The reinstall worked this time. I forgot to save my config, but I can just rebuild it. Thanks!
