### ISSUE TITLE
PFSense 2.6.0, Failed to install the following 1 package(s): https://pkg.freebsd.org/FreeBSD:12:amd64/latest/

### ISSUE THREAD

**Issue by mwilson007** [unofficial-unifi/unifi-pfsense#318]
I'm having issues running the script on a new PFSense 2.6.0 install.  I have it installed on 2.5.2 without any issues.  Any suggestions on how to resolve this error?

sh: mongod: not found
Mounting new filesystems... done.
Removing discontinued packages...
Usage: pkg lock [-lqy] [-a|[-Cgix] <pkg-name>]
       pkg lock --has-locked-packages
       pkg unlock [-lqy] [-a|[-Cgix] <pkg-name>]
For more information see 'pkg help lock'.
Usage: pkg delete [-DfnqRy] [-Cgix] <pkg-name> ...
       pkg delete [-Dnqy] -a

For more information see 'pkg help delete'.
 done.
Installing required packages...
packagesite.pkg                                       6708 kB 3321 kBps    02s
x packagesite.yaml.sig
x packagesite.yaml.pub
x packagesite.yaml
Package png-1.6.39 already installed.
Package brotli-1.0.9,1 already installed.
Package freetype2-2.12.1_2 already installed.
Package fontconfig-2.14.2,1 already installed.
Package alsa-lib-1.2.2_1 already installed.
Package mpdecimal-2.5.1 already installed.
Package python37-3.7.16_2 already installed.
Package libfontenc-1.1.4 already installed.
Package mkfontscale-1.2.1 already installed.
Package dejavu-2.37_1 already installed.
Package giflib-5.2.1 already installed.
Package xorgproto-2022.1 already installed.
Package libXdmcp-1.1.3 already installed.
Fetching : 100%    2 KiB   2.3kB/s    00:01
pkg: archive_read_open_filename(/tmp/.XXXXX): Unrecognized archive format

Failed to install the following 1 package(s): https://pkg.freebsd.org/FreeBSD:12:amd64/latest/

**Comment by tong2x** [comment]
which installer/script you used?

**Comment by mwilson007** [comment]
I used the following;

fetch -o - https://git.io/j7Jy | sh -s

**Comment by tong2x** [comment]
try #311 
and report what works

**Comment by mwilson007** [comment]
Thanks.  This one worked.

fetch -o - https://tinyurl.com/4fxzjrb5 | sh -s

**Comment by tong2x** [comment]
newer version/firmware did not work? or you have not tried yet?

**Comment by mwilson007** [comment]
I started from the top of the list and worked my way down until I found one that worked.
This was the newest version that worked.

fetch -o - https://tinyurl.com/4fxzjrb5 | sh -s

**Comment by tong2x** [comment]
could you post the error on the lastest or maybe last 2 if at all possible

**Comment by mwilson007** [comment]
The error was the exact same as the first post.

pkg: archive_read_open_filename(/tmp/.XXXXX): Unrecognized archive format

Failed to install the following 1 package(s): https://pkg.freebsd.org/FreeBSD:12:amd64/latest/

**Comment by tong2x** [comment]
hi 
are you willing to try out 
#317?

to test if it would fix the issue?

**Comment by mwilson007** [comment]
Hi.

Based on the info in #317, it is going to install version 7.2.97?  I already have a newer version that is installed and working using this script.

fetch -o - https://tinyurl.com/4fxzjrb5 | sh -s

**Comment by tong2x** [comment]
correct, if in case you want to try, I could also modified a newer script
than what you installed if you would like to try newer version

**Comment by mwilson007** [comment]
OK.  If you modify the script for the latest version 7.4.154, I will give it a try.

**Comment by tong2x** [comment]
please try #319

**Comment by mwilson007** [comment]
Thanks for the new script.  The install script completed but I cannot connect to the Unifi controller.  I get the following error.

HTTP Status 404 – Not Found

**Comment by mwilson007** [comment]
Correction.  It actually installed correctly.  It just took a bit of time for the service to start. No more errors.  I will restore my configuration and let you know if there are any more issues.  Thanks for your assistance.

**Comment by cram42** [comment]
> please try #319

Can confirm this works for me.
OPNsense 23.1.9-amd64

**Comment by timblaktu** [comment]
@tong2x I get this error running documented install command:

```
fetch -o - https://git.io/j7Jy | sh -s
```

... on a relatively fresh pfSense install from dev branch:

2.7.0-BETA (amd64)
built on Fri Jun 16 22:03:43 UTC 2023
FreeBSD 14.0-CURRENT

```
Fetching giflib-5.2.1.pkg: 100%  239 KiB 244.5kB/s    00:01
Installing giflib-5.2.1...
Extracting giflib-5.2.1: 100%
Fetching xorgproto-2022.1_1.pkg: 100%  231 KiB 237.0kB/s    00:01
Installing xorgproto-2022.1_1...
Extracting xorgproto-2022.1_1: 100%
Fetching libXdmcp-1.1.3.pkg: 100%   16 KiB  16.1kB/s    00:01
Installing libXdmcp-1.1.3...
Extracting libXdmcp-1.1.3: 100%
Fetching : 100%    2 KiB   2.3kB/s    00:01
pkg: archive_read_open_filename(/tmp/.XXXXX): Unrecognized archive format

Failed to install the following 1 package(s): https://pkg.freebsd.org/FreeBSD:14:amd64/latest/
```

I then found this and tried `fetch -o - https://tinyurl.com/bdzx6ks7 | sh -s` and the installation completed successfully, indicating it had started Unifi Controller. There were then several warnings that I believe prevented the service from starting successfully:

```
WARN Unable to load properties from '/usr/local/UniFi/data/system.properties' - /usr/local/UniFi/data/system.properties (No such f
ile or directory)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/local/UniFi/lib/tomcat-embed-core-9.0.65.jar) to field java.io.ObjectStreamC
lass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I'll reboot and work through these, let me know if you have any feedback or questions. Thanks!

**Comment by timblaktu** [comment]
Starting unifi.sh service complains about `Port 8080 not available`. @tong2x can you explain why the rc script is doing this right before starting the controller?

```
    # Open up netcat to listen on port 8080, and then close the connection immediately, then quit.
    # This works around the long startup delay. Thanks to gcohen55.
    echo "" | nc -l 127.0.0.1 8080 >/dev/null &
```

It seems like this is causing the 8080 port not available error, but this appears benign, since in my case, the controller is still running afterwards and I can connect via http via port 8080.

**Comment by tong2x** [comment]
`fetch -o - https://git.io/j7Jy | sh -s`
is really old and not application for current PFsense and OPNSense

`WARN Unable to load properties from '/usr/local/UniFi/data/system.properties' - /usr/local/UniFi/data/system.properties (No such f
ile or directory)`

has something to do with the files and or components.. probably java related component
it seems to be sort of normal now until the Unifi devs check it out, then again they probably wont.

after the install script, will automatically run unifi or start the service, some users report the it may take a while at first. you dont need to start unifi after pfsense reboot, unifi should start automatically (if not then you start it manually).

**Comment by timblaktu** [comment]
Thanks @tong2x. Is `master` the bleeding edge of this project? Its [README](https://github.com/unofficial-unifi/unifi-pfsense#usage) instructs users to install with `fetch -o - https://git.io/j7Jy | sh -s`, which is why I did it.

**Comment by tong2x** [comment]
no, it is supposed to be a stable release but was based on FREEBSD12, I believe.
with the changes to FREEBSD 13 some packages where removed.

Latest beta would be pullrequest #311 
pullrequest #319 specifically to solve some issues with PFsense 2.6

`fetch -o - https://tinyurl.com/bdzx6ks7 | sh -s`
this is however the latest beta
