### ISSUE TITLE
Unable to install on pfsenes 23.05.1

### ISSUE THREAD

**Issue by zajinx** [unofficial-unifi/unifi-pfsense#331]
Unable to install on pfsenes 23.05.1, this is a clean device nothing else configured on it, when i try to run the script (tride the one from master and official7.2.92 branch) i get the following error:

`[23.05.1-RELEASE][admin@pfSense]/root:   fetch -o - https://git.io/j7Jy | sh -s
-                                                     7663  B   17 MBps    00s
sh: mongod: not found
Mounting new filesystems... done.
Removing discontinued packages...
Usage: pkg lock [-lqy] [-a|[-Cgix] <pkg-name>]
       pkg lock --has-locked-packages
       pkg unlock [-lqy] [-a|[-Cgix] <pkg-name>]
For more information see 'pkg help lock'.
Usage: pkg delete [-DfnqRy] [-Cgix] <pkg-name> ...
       pkg delete [-Dnqy] -a

For more information see 'pkg help delete'.
 done.
Installing required packages...
packagesite.pkg                                       6709 kB   16 MBps    00s
x packagesite.yaml.sig
x packagesite.yaml.pub
x packagesite.yaml
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
35148701696:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/var/jenkins/workspace/pfSense-Plus-snapshots-23_05_1-main/sources/FreeBSD-src-plus-RELENG_23_05_1/crypto/openssl/ssl/statem/statem_clnt.c:1921:
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
35148701696:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/var/jenkins/workspace/pfSense-Plus-snapshots-23_05_1-main/sources/FreeBSD-src-plus-RELENG_23_05_1/crypto/openssl/ssl/statem/statem_clnt.c:1921:
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
35148701696:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/var/jenkins/workspace/pfSense-Plus-snapshots-23_05_1-main/sources/FreeBSD-src-plus-RELENG_23_05_1/crypto/openssl/ssl/statem/statem_clnt.c:1921:
pkg: https://pkgmir.geo.freebsd.org/FreeBSD:14:amd64/latest/All/png-1.6.40.pkg: Authentication error
[23.05.1-RELEASE][admin@pfSense]/root:
`

**Comment by tong2x** [comment]
there are issues with PFsense 2.7 relating to openssl
#324, #323, #320
