### ISSUE TITLE
Manual upgrade

### ISSUE THREAD

**Issue by dvdp** [unofficial-unifi/unifi-pfsense#85]
Not an issue but maybe useful - I've been using these simple steps about 10 times to upgrade my UniFi controller on our pfSense box - worked like a charm every time ...

# get the new version
cd ~
fetch https://www.ubnt.com/downloads/unifi/<version>/UniFi.unix.zip (or whatever the URL you have is).
unzip UniFi.unix.zip

# copy the data
cp -R /usr/local/UniFi/data ./UniFi/data

# compare snappyjava files
ls -al /usr/local/UniFi/lib/snappy* 
ls -al ./UniFi/lib/snappy* 

# evaluate and copy snappyjava if needed
cp /usr/local/UniFi/lib/snappy* ./UniFi/lib
# Note:
# When AP is stuck in 'Adopting' state, this is very likely related to snappy-java
Rename snappy-java so that it matches the name of the snappy-java in the new release if needed

# Stop unifi
service unifi.sh stop

# Backup and replace UniFi
mv /usr/local/UniFi /usr/local/UniFi_backup
mv UniFi /usr/local/
# Make symbolic link for mongod point to the right target
cd /usr/local/UniFi/bin
ls -al
rm mongod
ln -s /usr/local/bin/mongod mongod

# start unifi again
cd /usr/local/UniFi/lib
service unifi.sh start

**Comment by cypherstream** [comment]
Since the current script downloads 5.5.20, would these steps work to upgrade that to 5.5.24?

**Comment by cypherstream** [comment]
I tried this in a vm and no I could not get the web gui to load after downloading the 5.5.24 files.  I mv the files back.

**Comment by dvdp** [comment]
Yep going from 5.5.20 to 5.5.x should work fine - I ran this procedure about a dozen times now - always works like a charm.
I noticed that recent zip containers already contain a symbolic link for mongod, it is not pointing to the right location though so I added removal of the link to the procedure.
Used it a couple of minutes ago to upgrade from 5.6.19 to 5.6.20 - up and running.

**Comment by tong2x** [comment]
no update since 2017, closing for now
